// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend_system_service.Database;

#nullable disable

namespace backend_system_service.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230525114442_RWMMQTT")]
    partial class RWMMQTT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.1.23111.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Core.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingUnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastUsed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuildingUnitId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("Core.Entities.AutomationEmailNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AutomationSettingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("PreAlarmAutomationSettingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AutomationSettingId");

                    b.HasIndex("PreAlarmAutomationSettingId");

                    b.ToTable("AutomationEmailNotification");
                });

            modelBuilder.Entity("Core.Entities.AutomationSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingUnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuildingUnitId")
                        .IsUnique();

                    b.ToTable("AutomationSettings");
                });

            modelBuilder.Entity("Core.Entities.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("Core.Entities.BuildingUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("MqttText")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("SendMqttInfo")
                        .HasColumnType("boolean");

                    b.Property<bool>("SendPreAlarm")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("BuildingUnits");
                });

            modelBuilder.Entity("Core.Entities.FireAlarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingUnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsProbableFalseAlarm")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WasFalseAlarm")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BuildingUnitId");

                    b.ToTable("FireAlarms");
                });

            modelBuilder.Entity("Core.Entities.Gateway", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsInitialized")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastContact")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("Password")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Username")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Gateways");
                });

            modelBuilder.Entity("Core.Entities.Header", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("HttpNotificationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HttpNotificationId");

                    b.ToTable("Header");
                });

            modelBuilder.Entity("Core.Entities.HttpNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AutomationSettingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Method")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("NotificationSettingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PreAlarmAutomationSettingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AutomationSettingId");

                    b.HasIndex("NotificationSettingId");

                    b.HasIndex("PreAlarmAutomationSettingId");

                    b.ToTable("HttpNotification");
                });

            modelBuilder.Entity("Core.Entities.MqttConnectionData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Username")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BuildingUnitId");

                    b.ToTable("MqttConnectionData");
                });

            modelBuilder.Entity("Core.Entities.NotificationSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("EmailNotification")
                        .HasColumnType("boolean");

                    b.Property<bool>("HttpNotification")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneCallNotification")
                        .HasColumnType("boolean");

                    b.Property<bool>("PushNotification")
                        .HasColumnType("boolean");

                    b.Property<bool>("SmsNotification")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("Core.Entities.PhoneCallNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AutomationSettingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("NotificationSettingId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("PreAlarmAutomationSettingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AutomationSettingId");

                    b.HasIndex("NotificationSettingId")
                        .IsUnique();

                    b.HasIndex("PreAlarmAutomationSettingId");

                    b.ToTable("PhoneCallNotification");
                });

            modelBuilder.Entity("Core.Entities.PreAlarmAutomationSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingUnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuildingUnitId")
                        .IsUnique();

                    b.ToTable("PreAlarmAutomationSettings");
                });

            modelBuilder.Entity("Core.Entities.PushNotificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("NotificationSettingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NotificationSettingId");

                    b.ToTable("PushNotificationToken");
                });

            modelBuilder.Entity("Core.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingUnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuildingUnitId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Core.Entities.SmokeDetector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("BatteryLevel")
                        .HasColumnType("double precision");

                    b.Property<bool>("BatteryLow")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsViaMqtt")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastBatteryReplacement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastMaintenance")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MqttMessage")
                        .HasColumnType("text");

                    b.Property<string>("MqttTopic")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("RawTransmissionData")
                        .HasColumnType("text");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SmokeDetectorModelId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("SmokeDetectorModelId");

                    b.ToTable("SmokeDetectors");
                });

            modelBuilder.Entity("Core.Entities.SmokeDetectorAlarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("FireAlarmId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("SmokeDetectorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FireAlarmId");

                    b.HasIndex("SmokeDetectorId");

                    b.ToTable("SmokeDetectorAlarms");
                });

            modelBuilder.Entity("Core.Entities.SmokeDetectorMaintenance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsBatteryReplaced")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCleaned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDustCleaned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTested")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SmokeDetectorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SmokeDetectorId");

                    b.ToTable("SmokeDetectorMaintenances");
                });

            modelBuilder.Entity("Core.Entities.SmokeDetectorModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BatteryReplacementInterval")
                        .HasColumnType("integer");

                    b.Property<int>("CommunicationType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("MaintenanceInterval")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("SmokeDetectorProtocol")
                        .HasColumnType("integer");

                    b.Property<bool>("SupportsBatteryAlarm")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsRemoteAlarm")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SmokeDetectorModels");
                });

            modelBuilder.Entity("Core.Entities.SmsNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AutomationSettingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("NotificationSettingId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NotificationSettingId")
                        .IsUnique();

                    b.ToTable("SmsNotification");

                    b.HasDiscriminator<string>("Discriminator").HasValue("SmsNotification");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Core.Entities.UserEmailNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("NotificationSettingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NotificationSettingId")
                        .IsUnique();

                    b.ToTable("UserEmailNotification");
                });

            modelBuilder.Entity("Core.Entities.AutomationSmsNotification", b =>
                {
                    b.HasBaseType("Core.Entities.SmsNotification");

                    b.Property<Guid?>("PreAlarmAutomationSettingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasIndex("AutomationSettingId");

                    b.HasIndex("PreAlarmAutomationSettingId");

                    b.HasDiscriminator().HasValue("AutomationSmsNotification");
                });

            modelBuilder.Entity("Core.Entities.Address", b =>
                {
                    b.HasOne("Core.Entities.Building", "Building")
                        .WithOne("Address")
                        .HasForeignKey("Core.Entities.Address", "BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Core.Entities.ApiKey", b =>
                {
                    b.HasOne("Core.Entities.BuildingUnit", "BuildingUnit")
                        .WithMany("ApiKeys")
                        .HasForeignKey("BuildingUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuildingUnit");
                });

            modelBuilder.Entity("Core.Entities.AutomationEmailNotification", b =>
                {
                    b.HasOne("Core.Entities.AutomationSetting", "AutomationSetting")
                        .WithMany("EmailNotifications")
                        .HasForeignKey("AutomationSettingId");

                    b.HasOne("Core.Entities.PreAlarmAutomationSetting", null)
                        .WithMany("EmailNotifications")
                        .HasForeignKey("PreAlarmAutomationSettingId");

                    b.Navigation("AutomationSetting");
                });

            modelBuilder.Entity("Core.Entities.AutomationSetting", b =>
                {
                    b.HasOne("Core.Entities.BuildingUnit", "BuildingUnit")
                        .WithOne("AutomationSetting")
                        .HasForeignKey("Core.Entities.AutomationSetting", "BuildingUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuildingUnit");
                });

            modelBuilder.Entity("Core.Entities.Building", b =>
                {
                    b.HasOne("Core.Entities.Tenant", "Tenant")
                        .WithMany("Buildings")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Core.Entities.BuildingUnit", b =>
                {
                    b.HasOne("Core.Entities.Building", "Building")
                        .WithMany("BuildingUnits")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Core.Entities.FireAlarm", b =>
                {
                    b.HasOne("Core.Entities.BuildingUnit", "BuildingUnit")
                        .WithMany("FireAlarms")
                        .HasForeignKey("BuildingUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuildingUnit");
                });

            modelBuilder.Entity("Core.Entities.Gateway", b =>
                {
                    b.HasOne("Core.Entities.Room", "Room")
                        .WithMany("Gateways")
                        .HasForeignKey("RoomId");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Core.Entities.Header", b =>
                {
                    b.HasOne("Core.Entities.HttpNotification", "HttpNotification")
                        .WithMany("Headers")
                        .HasForeignKey("HttpNotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HttpNotification");
                });

            modelBuilder.Entity("Core.Entities.HttpNotification", b =>
                {
                    b.HasOne("Core.Entities.AutomationSetting", "AutomationSetting")
                        .WithMany("HttpNotifications")
                        .HasForeignKey("AutomationSettingId");

                    b.HasOne("Core.Entities.NotificationSetting", "NotificationSetting")
                        .WithMany("HttpNotifications")
                        .HasForeignKey("NotificationSettingId");

                    b.HasOne("Core.Entities.PreAlarmAutomationSetting", null)
                        .WithMany("HttpNotifications")
                        .HasForeignKey("PreAlarmAutomationSettingId");

                    b.Navigation("AutomationSetting");

                    b.Navigation("NotificationSetting");
                });

            modelBuilder.Entity("Core.Entities.MqttConnectionData", b =>
                {
                    b.HasOne("Core.Entities.BuildingUnit", "BuildingUnit")
                        .WithMany("MqttConnectionData")
                        .HasForeignKey("BuildingUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuildingUnit");
                });

            modelBuilder.Entity("Core.Entities.PhoneCallNotification", b =>
                {
                    b.HasOne("Core.Entities.AutomationSetting", "AutomationSetting")
                        .WithMany("PhoneCallNotifications")
                        .HasForeignKey("AutomationSettingId");

                    b.HasOne("Core.Entities.NotificationSetting", "NotificationSetting")
                        .WithOne("PhoneNumber")
                        .HasForeignKey("Core.Entities.PhoneCallNotification", "NotificationSettingId");

                    b.HasOne("Core.Entities.PreAlarmAutomationSetting", null)
                        .WithMany("PhoneCallNotifications")
                        .HasForeignKey("PreAlarmAutomationSettingId");

                    b.Navigation("AutomationSetting");

                    b.Navigation("NotificationSetting");
                });

            modelBuilder.Entity("Core.Entities.PreAlarmAutomationSetting", b =>
                {
                    b.HasOne("Core.Entities.BuildingUnit", "BuildingUnit")
                        .WithOne("PreAlarmNotification")
                        .HasForeignKey("Core.Entities.PreAlarmAutomationSetting", "BuildingUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuildingUnit");
                });

            modelBuilder.Entity("Core.Entities.PushNotificationToken", b =>
                {
                    b.HasOne("Core.Entities.NotificationSetting", "NotificationSetting")
                        .WithMany("PushNotificationTokens")
                        .HasForeignKey("NotificationSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationSetting");
                });

            modelBuilder.Entity("Core.Entities.Room", b =>
                {
                    b.HasOne("Core.Entities.BuildingUnit", "BuildingUnit")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuildingUnit");
                });

            modelBuilder.Entity("Core.Entities.SmokeDetector", b =>
                {
                    b.HasOne("Core.Entities.Room", "Room")
                        .WithMany("SmokeDetectors")
                        .HasForeignKey("RoomId");

                    b.HasOne("Core.Entities.SmokeDetectorModel", "SmokeDetectorModel")
                        .WithMany("SmokeDetectors")
                        .HasForeignKey("SmokeDetectorModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("SmokeDetectorModel");
                });

            modelBuilder.Entity("Core.Entities.SmokeDetectorAlarm", b =>
                {
                    b.HasOne("Core.Entities.FireAlarm", "FireAlarm")
                        .WithMany("AlarmedDetectors")
                        .HasForeignKey("FireAlarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.SmokeDetector", "SmokeDetector")
                        .WithMany("Events")
                        .HasForeignKey("SmokeDetectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FireAlarm");

                    b.Navigation("SmokeDetector");
                });

            modelBuilder.Entity("Core.Entities.SmokeDetectorMaintenance", b =>
                {
                    b.HasOne("Core.Entities.SmokeDetector", "SmokeDetector")
                        .WithMany("Maintenances")
                        .HasForeignKey("SmokeDetectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SmokeDetector");
                });

            modelBuilder.Entity("Core.Entities.SmsNotification", b =>
                {
                    b.HasOne("Core.Entities.NotificationSetting", "NotificationSetting")
                        .WithOne("SmsNumber")
                        .HasForeignKey("Core.Entities.SmsNotification", "NotificationSettingId");

                    b.Navigation("NotificationSetting");
                });

            modelBuilder.Entity("Core.Entities.UserEmailNotification", b =>
                {
                    b.HasOne("Core.Entities.NotificationSetting", "NotificationSetting")
                        .WithOne("Email")
                        .HasForeignKey("Core.Entities.UserEmailNotification", "NotificationSettingId");

                    b.Navigation("NotificationSetting");
                });

            modelBuilder.Entity("Core.Entities.AutomationSmsNotification", b =>
                {
                    b.HasOne("Core.Entities.AutomationSetting", "AutomationSetting")
                        .WithMany("SmsNotifications")
                        .HasForeignKey("AutomationSettingId");

                    b.HasOne("Core.Entities.PreAlarmAutomationSetting", null)
                        .WithMany("SmsNotifications")
                        .HasForeignKey("PreAlarmAutomationSettingId");

                    b.Navigation("AutomationSetting");
                });

            modelBuilder.Entity("Core.Entities.AutomationSetting", b =>
                {
                    b.Navigation("EmailNotifications");

                    b.Navigation("HttpNotifications");

                    b.Navigation("PhoneCallNotifications");

                    b.Navigation("SmsNotifications");
                });

            modelBuilder.Entity("Core.Entities.Building", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("BuildingUnits");
                });

            modelBuilder.Entity("Core.Entities.BuildingUnit", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("AutomationSetting")
                        .IsRequired();

                    b.Navigation("FireAlarms");

                    b.Navigation("MqttConnectionData");

                    b.Navigation("PreAlarmNotification")
                        .IsRequired();

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Core.Entities.FireAlarm", b =>
                {
                    b.Navigation("AlarmedDetectors");
                });

            modelBuilder.Entity("Core.Entities.HttpNotification", b =>
                {
                    b.Navigation("Headers");
                });

            modelBuilder.Entity("Core.Entities.NotificationSetting", b =>
                {
                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("HttpNotifications");

                    b.Navigation("PhoneNumber")
                        .IsRequired();

                    b.Navigation("PushNotificationTokens");

                    b.Navigation("SmsNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.PreAlarmAutomationSetting", b =>
                {
                    b.Navigation("EmailNotifications");

                    b.Navigation("HttpNotifications");

                    b.Navigation("PhoneCallNotifications");

                    b.Navigation("SmsNotifications");
                });

            modelBuilder.Entity("Core.Entities.Room", b =>
                {
                    b.Navigation("Gateways");

                    b.Navigation("SmokeDetectors");
                });

            modelBuilder.Entity("Core.Entities.SmokeDetector", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Maintenances");
                });

            modelBuilder.Entity("Core.Entities.SmokeDetectorModel", b =>
                {
                    b.Navigation("SmokeDetectors");
                });

            modelBuilder.Entity("Core.Entities.Tenant", b =>
                {
                    b.Navigation("Buildings");
                });
#pragma warning restore 612, 618
        }
    }
}
